# Generated by Django 2.2.5 on 2019-09-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('amount', models.PositiveIntegerField(verbose_name='Amount #')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registered on')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('lost', models.BooleanField(default=False, verbose_name='Not in possession')),
            ],
        ),
    ]
